using EmbroideryWorkerManagement.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EmbroideryWorkerManagement.Services
{
    public class PaymentSlipPdfService
    {
        public byte[] GeneratePdf(MonthlyPayment payment)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header().Text("Payment Slip").SemiBold().FontSize(20).AlignCenter();

                    page.Content().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(2);
                        });

                        table.Cell().Element(CellStyle).Text("Worker Name:");
                        table.Cell().Element(CellStyle).Text(payment.Worker.Name);

                        table.Cell().Element(CellStyle).Text("Month:");
                        table.Cell().Element(CellStyle).Text($"{payment.Month}/{payment.Year}");

                        table.Cell().Element(CellStyle).Text("Base Salary:");
                        table.Cell().Element(CellStyle).Text($"{payment.BaseSalary:N2}");

                        table.Cell().Element(CellStyle).Text("Attendance Bonus:");
                        table.Cell().Element(CellStyle).Text($"{payment.AttendanceBonus:N2}");

                        table.Cell().Element(CellStyle).Text("Extra Production Bonus:");
                        table.Cell().Element(CellStyle).Text($"{payment.ExtraProductionBonus:N2}");

                        table.Cell().Element(CellStyle).Text("Advance Deduction:");
                        table.Cell().Element(CellStyle).Text($"-{payment.AdvanceDeduction:N2}");

                        table.Cell().Element(CellStyle).Text("Total Salary:");
                        table.Cell().Element(CellStyle).Text($"{payment.TotalSalary:N2}");

                        table.Cell().Element(CellStyle).Text("Paid Amount:");
                        table.Cell().Element(CellStyle).Text($"{payment.PaidAmount:N2}");

                        table.Cell().Element(CellStyle).Text("Due Amount:");
                        table.Cell().Element(CellStyle).Text($"{payment.DueAmount:N2}");
                    });

                    page.Footer().AlignCenter().Text("Generated by Embroidery Worker ERP");
                });
            });

            return document.GeneratePdf();
        }

        private IContainer CellStyle(IContainer container)
        {
            return container.PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
        }
    }
}
